services:
  - type: web
    name: keyword-insights-api
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip
      pip3 install pytrends pandas
      npm install
    startCommand: node server.js
